[I 2025-08-09 20:18:36,976] A new study created in memory with name: no-name-ee9ed8ae-95a4-42e1-ad57-d34e618aaa02
Mode-0 approx rank: 9/38
Estimated noise variance from mode-0: 0.0
Mode-1 approx rank: 12/17
Estimated noise variance from mode-1: 0.001126904808615485
Mode-2 approx rank: 15/24
Estimated noise variance from mode-2: 0.0007391924716809495
Mode-3 approx rank: 24/60
Estimated noise variance from mode-3: 0.0003892046506993127
  0%|          | 0/500 [00:00<?, ?it/s]                                         0%|          | 0/500 [00:01<?, ?it/s]                                         0%|          | 0/500 [00:01<?, ?it/s]  0%|          | 0/500 [00:01<?, ?it/s]
[W 2025-08-09 20:18:38,635] Trial 0 failed with parameters: {'psi': 0.35570752193647015, 'lda_t': 0.0005740290846075164} because of the following error: RuntimeError('CUDA error: invalid device ordinal\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n').
Traceback (most recent call last):
  File "/mnt/home/mondalra/miniforge3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/mnt/ffs24/home/mondalra/Anomaly_Detection/smd_anomaly_detection/jobs_lrsts/LRSTS.py", line 132, in lrsts_objective
    lr_sts= SNN__LOGN_GTV(Y, G, lr_modes=[1,2,3,4], graph_modes=[1], gtvr_config=gtvr_config,
  File "/mnt/ffs24/home/mondalra/Anomaly_Detection/src/models/lr_ssd/snn__logn_gtv.py", line 85, in __init__
    self.Y = torch.tensor(Y, device=self.device, dtype=self.dtype)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[W 2025-08-09 20:18:38,652] Trial 0 failed with value None.
Traceback (most recent call last):
  File "/mnt/ffs24/home/mondalra/Anomaly_Detection/smd_anomaly_detection/jobs_lrsts/LRSTS.py", line 197, in <module>
    study.optimize(lrsts_objective, n_trials=500, show_progress_bar=True)
  File "/mnt/home/mondalra/miniforge3/lib/python3.10/site-packages/optuna/study/study.py", line 489, in optimize
    _optimize(
  File "/mnt/home/mondalra/miniforge3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 64, in _optimize
    _optimize_sequential(
  File "/mnt/home/mondalra/miniforge3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 161, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/mnt/home/mondalra/miniforge3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 253, in _run_trial
    raise func_err
  File "/mnt/home/mondalra/miniforge3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/mnt/ffs24/home/mondalra/Anomaly_Detection/smd_anomaly_detection/jobs_lrsts/LRSTS.py", line 132, in lrsts_objective
    lr_sts= SNN__LOGN_GTV(Y, G, lr_modes=[1,2,3,4], graph_modes=[1], gtvr_config=gtvr_config,
  File "/mnt/ffs24/home/mondalra/Anomaly_Detection/src/models/lr_ssd/snn__logn_gtv.py", line 85, in __init__
    self.Y = torch.tensor(Y, device=self.device, dtype=self.dtype)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

